name: Build and Release

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: > 
            mingw-w64-x86_64-gcc 
            mingw-w64-x86_64-cmake 
            mingw-w64-x86_64-make 
            mingw-w64-x86_64-runtime  # Ensures runtime DLLs like libwinpthread-1.dll are installed

      - name: Configure CMake
        run: cmake -B build -G "MinGW Makefiles"

      - name: Build project
        run: cmake --build build --config Release

      # Dynamically find and copy libwinpthread-1.dll
      - name: Copy required DLLs
        shell: pwsh
        run: |
          $DLLPath = Get-ChildItem -Path "C:/msys64/mingw64/bin/" -Filter "libwinpthread-1.dll" -Recurse | Select-Object -ExpandProperty FullName -First 1
          if ($DLLPath) {
            Copy-Item -Path $DLLPath -Destination build/
          } else {
            Write-Error "libwinpthread-1.dll not found!"
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Executable
          path: |
            build/OpenGLWin32.exe
            build/libwinpthread-1.dll

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows-Executable
          path: build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            build/OpenGLWin32.exe
            build/libwinpthread-1.dll
          prerelease: true
          generate_release_notes: true
          name: "Automated Build - Latest"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
