name: Build and Release

on:
  push:
    branches:
      - main  # Runs on every push to the master branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make

      - name: Configure CMake
        run: cmake -B build -G "MinGW Makefiles"

      - name: Build project
        run: cmake --build build --config Release

      - name: Rename executable
        run: mv build/OpenGLWin32.exe build/OpenGLWin32.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Executable
          path: build/OpenGLWin32.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows-Executable
          path: build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest  # Always updates the 'latest' release
          files: build/OpenGLWin32.exe
          prerelease: true  # Marks as pre-release to avoid conflicts
          generate_release_notes: true
          name: "Automated Build - Latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
